URL_WEATHER_ARCHIVE = "https://archive-api.open-meteo.com/v1/archive"
URL_WEATHER_FORECAST = "https://api.open-meteo.com/v1/forecast"
LATITUDE = 47.1221
LONGITUDE = 9.486
BACKFILL_START_DATE = "2022-01-01"
WEATHER_DAILY_VARS = ["temperature_2m_max", "temperature_2m_min", "precipitation_sum"]
TIMEZONE = "Europe/Zurich"
URL_ENTSOE = "https://web-api.tp.entsoe.eu/api"
DOCUMENT_TYPE = "A65"
PROCESS_TYPE = "A16"
OUT_BIDDING_ZONE_DOMAIN = "10YCH-SWISSGRIDZ"
